apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: carteira-bronze-{{ ts_nodash | lower }}
  namespace: spark-operator
spec:
  volumes:
    - name: ivy
      emptyDir: {}
  sparkConf:
    spark.driver.extraJavaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp, -Dcom.amazonaws.services.s3.enableV4=true"
    spark.executor.extraJavaOptions: "-Dcom.amazonaws.services.s3.enableV4=true"
    spark.kubernetes.allocation.batch.size: "10"
    spark.sql.extensions: "io.delta.sql.DeltaSparkSessionExtension"
    spark.sql.catalog.spark_catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"
    spark.databricks.delta.schema.autoMerge.enabled: "true"
  hadoopConf:
    fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    fs.s3a.path.style.access: "True"
  type: Python
  pythonVersion: "3"
  image: "andonokar/testespark:1.1"
  imagePullPolicy: Always
  imagePullSecrets:
    - docker-pass
  mainApplicationFile: "local:///app/e2etest.py"
  arguments:
    - "csn"
    - "CARTEIRA"
    - "bronze"
  sparkVersion: "3.3.1"
  restartPolicy:
    type: Never
  driver:
#    envSecretKeyRefs:
#      AWS_ACCESS_KEY_ID:
#        name: aws-secret
#        key: awsAccessKeyId
#      AWS_SECRET_ACCESS_KEY:
#        name: aws-secret
#        key: awsSecretAccessKey
    cores: 1
    coreRequest: "500m"
    coreLimit: "1200m"
    memory: "2g"
    labels:
      version: 3.3.2
    volumeMounts:
      - name: ivy
        mountPath: /tmp
  executor:
#    envSecretKeyRefs:
#      AWS_ACCESS_KEY_ID:
#        name: aws-secret
#        key: awsAccessKeyId
#      AWS_SECRET_ACCESS_KEY:
#        name: aws-secret
#        key: awsSecretAccessKey
    cores: 1
    coreRequest: "500m"
    instances: 2
    memory: "4g"
    labels:
      version: 3.3.1
    volumeMounts:
      - name: ivy
        mountPath: /tmp
